create table if not exists question (
    id int primary key generated by default as identity,
    content varchar unique not null
);

create table if not exists task (
    id int primary key generated by default as identity,
    content varchar unique not null
);
